"""change user_loc.user_id.unique to True

Revision ID: 7138c51f12e8
Revises: abda8af456a5
Create Date: 2023-03-06 12:46:28.346111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7138c51f12e8'
down_revision = 'abda8af456a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_loc', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_loc', type_='unique')
    # ### end Alembic commands ###
